// src/lib/component-scanner/puck-adapter.ts
// 将 ScannedComponent 转换为 Puck ComponentConfig 格式的代码字符串

import type { PropDef, ScannedComponent } from "./types"

/** JavaScript 保留字，不能用作标识符 */
const JS_RESERVED_WORDS = new Set([
  "abstract", "arguments", "async", "await", "boolean", "break", "byte",
  "case", "catch", "char", "class", "const", "continue", "debugger",
  "default", "delete", "do", "double", "else", "enum", "export",
  "extends", "false", "final", "finally", "float", "for", "function",
  "goto", "if", "implements", "import", "in", "instanceof", "int",
  "interface", "let", "long", "native", "new", "null", "package",
  "private", "protected", "public", "return", "short", "static",
  "super", "switch", "synchronized", "this", "throw", "throws",
  "transient", "true", "try", "typeof", "var", "void", "volatile",
  "while", "with", "yield",
])

/** 将组件名转为安全的 JS 标识符（保留字加下划线后缀） */
function safeIdentifier(name: string): string {
  if (JS_RESERVED_WORDS.has(name)) {
    return `${name}_`
  }
  if (/^\d/.test(name)) {
    return `_${name}`
  }
  return name
}

/** 将 PropDef 类型映射为 Puck field 类型 */
function mapPropTypeToPuckField(prop: PropDef): string {
  switch (prop.type) {
    case "select":
      return "select"
    case "boolean":
      return "switch"
    case "number":
      return "number"
    case "string":
      return "text"
    case "object":
      return "object"
    case "array":
      return "array"
    case "unknown":
    default:
      return "text"
  }
}

/** 生成 Puck field 定义的代码字符串 */
function generateFieldCode(prop: PropDef): string {
  const puckType = mapPropTypeToPuckField(prop)

  if (puckType === "select" && prop.options && prop.options.length > 0) {
    const optionsStr = prop.options
      .map((opt) => JSON.stringify({ label: opt, value: opt }))
      .join(",\n        ")
    return `{\n        type: "select",\n        options: [\n          ${optionsStr}\n        ]\n      }`
  }

  if (puckType === "switch") {
    return `{ type: "switch" }`
  }

  if (puckType === "number") {
    return `{ type: "number" }`
  }

  if (puckType === "object") {
    return `{ type: "object" }`
  }

  if (puckType === "array") {
    return `{ type: "array" }`
  }

  // text / unknown → text
  return `{ type: "text" }`
}

/** 生成默认值代码字符串 */
function generateDefaultValue(value: unknown): string {
  if (value === null || value === undefined) return "undefined"
  if (typeof value === "string") return JSON.stringify(value)
  if (typeof value === "number") return String(value)
  if (typeof value === "boolean") return String(value)
  if (Array.isArray(value)) return JSON.stringify(value)
  if (typeof value === "object") return JSON.stringify(value)
  return String(value)
}

/** 获取默认值（用于 Puck defaultProps） */
function getDefaultForProp(prop: PropDef): unknown {
  if (prop.defaultValue !== undefined) return prop.defaultValue

  switch (prop.type) {
    case "string":
      return ""
    case "select":
      return prop.options?.[0] ?? ""
    case "number":
      return 0
    case "boolean":
      return false
    case "unknown":
      return ""
    default:
      return undefined
  }
}

/** 将 ScannedComponent 生成 Puck ComponentConfig 代码字符串 */
export function generatePuckComponentCode(component: ScannedComponent): string {
  const { name, props } = component
  const safeName = safeIdentifier(name)

  // 生成 fields 代码
  const fieldsCode = props
    .map((prop) => `    ${prop.name}: ${generateFieldCode(prop)}`)
    .join(",\n")

  // 生成 defaultProps 代码
  const defaultPropsEntries = props
    .map((prop) => {
      const val = getDefaultForProp(prop)
      if (val === undefined) return null
      return `    ${prop.name}: ${generateDefaultValue(val)}`
    })
    .filter(Boolean)
    .join(",\n")

  const defaultPropsCode = defaultPropsEntries
    ? `,\n  defaultProps: {\n${defaultPropsEntries}\n  }`
    : ""

  // 生成描述注释（JSDoc）
  const descriptionLines: string[] = []
  for (const prop of props) {
    if (prop.description) {
      descriptionLines.push(`   * @property ${prop.name} - ${prop.description}`)
    }
  }
  const jsdocBlock =
    descriptionLines.length > 0
      ? `/**\n${descriptionLines.join("\n")}\n */\n`
      : ""

  return `${jsdocBlock}${name}: {\n  render: (props: any) => React.createElement(${safeName}, props),\n  fields: {\n${fieldsCode}\n  }${defaultPropsCode}\n}`
}

/** 为 Vite Plugin 生成完整的 registry 文件内容 */
export function generateRegistryFileContent(components: ScannedComponent[]): string {
  if (components.length === 0) {
    return `// Auto-generated by component-scanner — no components found
// Do not edit manually. This file is overwritten during dev/build.

export const scannedComponents: Record<string, unknown> = {}
`
  }

  // 生成 import 语句
  // registry 文件位于 src/.pageforge/registry.ts，组件在 src/components/ 等
  // 所以相对路径从 registry.ts 到组件文件需要回溯一级
  const imports = components
    .map((comp) => {
      const importPath = comp.filePath.replace(/\.tsx$/, "")
      // filePath 是相对于项目根的，如 "src/components/HeroBanner.tsx"
      // registry 在 "src/.pageforge/registry.ts"，所以 import 路径为 "../${importPath.slice(4)}"
      // 即去掉 "src/" 前缀，加上 "../"
      const relPath = `../${importPath.slice(4)}`
      const safeName = safeIdentifier(comp.name)
      return `import ${safeName} from "${relPath}"`
    })
    .join("\n")

  // 生成每个组件的 Puck config
  const configs = components.map((comp) => generatePuckComponentCode(comp)).join(",\n\n")

  return `// Auto-generated by component-scanner — do not edit manually
// Generated at: ${new Date().toISOString()}
import React from "react"

${imports}

export const scannedComponents: Record<string, any> = {
${configs},
}
`
}
