// Auto-generated by component-scanner — do not edit manually
// Generated at: 2026-07-09T23:01:48.654Z
import React from "react"

import AuthGuard from "../components/AuthGuard"
import FieldRenderer from "../components/FieldRenderer"
import HeroBanner from "../components/HeroBanner"
import InspectorPanel from "../components/Inspector/InspectorPanel"
import PropsView from "../components/Inspector/PropsView"
import PuckSelectionSync from "../components/Inspector/PuckSelectionSync"
import TreeView from "../components/Inspector/TreeView"

export const scannedComponents: Record<string, any> = {
AuthGuard: {
  render: (props: any) => React.createElement(AuthGuard, props),
  fields: {
    children: { type: "text" }
  },
  defaultProps: {
    children: ""
  }
},

FieldRenderer: {
  render: (props: any) => React.createElement(FieldRenderer, props),
  fields: {

  }
},

/**
   * @property title - 主标题文字
   * @property subtitle - 副标题文字
   * @property buttonText - 按钮文字
   * @property buttonUrl - 按钮链接
   * @property variant - 主题色变体
   * @property showDecorations - 是否显示装饰元素
   * @property padding - 内边距（px）
 */
HeroBanner: {
  render: (props: any) => React.createElement(HeroBanner, props),
  fields: {
    title: { type: "text" },
    subtitle: { type: "text" },
    buttonText: { type: "text" },
    buttonUrl: { type: "text" },
    variant: {
        type: "select",
        options: [
          {"label":"light","value":"light"},
        {"label":"dark","value":"dark"},
        {"label":"gradient","value":"gradient"}
        ]
      },
    showDecorations: { type: "switch" },
    padding: { type: "number" }
  },
  defaultProps: {
    title: "",
    subtitle: "",
    buttonText: "",
    buttonUrl: "",
    variant: "light",
    showDecorations: false,
    padding: 0
  }
},

InspectorPanel: {
  render: (props: any) => React.createElement(InspectorPanel, props),
  fields: {
    data: { type: "object" },
    visible: { type: "switch" },
    selectedId: { type: "text" },
    onSelect: { type: "object" },
    onPropChange: { type: "object" },
    onClose: { type: "object" }
  },
  defaultProps: {
    visible: false,
    selectedId: ""
  }
},

PropsView: {
  render: (props: any) => React.createElement(PropsView, props),
  fields: {
    data: { type: "object" },
    selectedId: { type: "text" },
    onPropChange: { type: "object" }
  },
  defaultProps: {
    selectedId: ""
  }
},

/**
   * @property selectedId - Editor 维护的选中 ID
   * @property onSelect - 画布选中变化时的回调
   * @property handleRef - 暴露操作句柄的 ref
 */
PuckSelectionSync: {
  render: (props: any) => React.createElement(PuckSelectionSync, props),
  fields: {
    selectedId: { type: "text" },
    onSelect: { type: "object" },
    handleRef: { type: "text" }
  },
  defaultProps: {
    selectedId: "",
    handleRef: ""
  }
},

TreeView: {
  render: (props: any) => React.createElement(TreeView, props),
  fields: {
    data: { type: "object" },
    selectedId: { type: "text" },
    onSelect: { type: "object" }
  },
  defaultProps: {
    selectedId: ""
  }
},
}
