// src/puck/theme/presets.ts
// 5 个预设主题数据，每个包含 name / description / variables。
// variables 为常用 CSS 自定义属性键值对。

export interface PresetTheme {
  name: string
  description: string
  variables: Record<string, string>
}

export const presetThemes: PresetTheme[] = [
  {
    name: "浅色",
    description: "明亮的浅色默认主题，适合大多数页面",
    variables: {
      "--primary": "#6366f1",
      "--primary-foreground": "#ffffff",
      "--background": "#ffffff",
      "--foreground": "#0f172a",
      "--muted": "#f1f5f9",
      "--muted-foreground": "#64748b",
      "--accent": "#f1f5f9",
      "--accent-foreground": "#0f172a",
      "--border": "#e2e8f0",
      "--ring": "#6366f1",
      "--radius": "0.5rem",
      "--font-family": "Inter, system-ui, -apple-system, sans-serif",
      "--shadow-sm": "0 1px 2px 0 rgb(0 0 0 / 0.05)",
      "--shadow-md": "0 4px 6px -1px rgb(0 0 0 / 0.1)",
      "--card-background": "#ffffff",
      "--card-border": "#e2e8f0",
      "--input-background": "#ffffff",
      "--input-border": "#e2e8f0",
    },
  },
  {
    name: "深色",
    description: "深色背景主题，适合夜间阅读或暗色风格页面",
    variables: {
      "--primary": "#818cf8",
      "--primary-foreground": "#0f172a",
      "--background": "#0f172a",
      "--foreground": "#e2e8f0",
      "--muted": "#1e293b",
      "--muted-foreground": "#94a3b8",
      "--accent": "#1e293b",
      "--accent-foreground": "#e2e8f0",
      "--border": "#334155",
      "--ring": "#818cf8",
      "--radius": "0.5rem",
      "--font-family": "Inter, system-ui, -apple-system, sans-serif",
      "--shadow-sm": "0 1px 2px 0 rgb(0 0 0 / 0.3)",
      "--shadow-md": "0 4px 6px -1px rgb(0 0 0 / 0.4)",
      "--card-background": "#1e293b",
      "--card-border": "#334155",
      "--input-background": "#1e293b",
      "--input-border": "#334155",
    },
  },
  {
    name: "科技蓝",
    description: "蓝色科技感主题，适合技术类或企业页面",
    variables: {
      "--primary": "#2563eb",
      "--primary-foreground": "#ffffff",
      "--background": "#f8fafc",
      "--foreground": "#0f172a",
      "--muted": "#eff6ff",
      "--muted-foreground": "#64748b",
      "--accent": "#dbeafe",
      "--accent-foreground": "#1e40af",
      "--border": "#bfdbfe",
      "--ring": "#2563eb",
      "--radius": "0.375rem",
      "--font-family": "Inter, system-ui, -apple-system, sans-serif",
      "--shadow-sm": "0 1px 2px 0 rgb(37 99 235 / 0.08)",
      "--shadow-md": "0 4px 6px -1px rgb(37 99 235 / 0.12)",
      "--card-background": "#ffffff",
      "--card-border": "#bfdbfe",
      "--input-background": "#ffffff",
      "--input-border": "#bfdbfe",
    },
  },
  {
    name: "自然绿",
    description: "自然绿色主题，适合环保、健康或户外类页面",
    variables: {
      "--primary": "#16a34a",
      "--primary-foreground": "#ffffff",
      "--background": "#f0fdf4",
      "--foreground": "#052e16",
      "--muted": "#dcfce7",
      "--muted-foreground": "#166534",
      "--accent": "#bbf7d0",
      "--accent-foreground": "#14532d",
      "--border": "#86efac",
      "--ring": "#16a34a",
      "--radius": "0.5rem",
      "--font-family": "Inter, system-ui, -apple-system, sans-serif",
      "--shadow-sm": "0 1px 2px 0 rgb(22 163 74 / 0.08)",
      "--shadow-md": "0 4px 6px -1px rgb(22 163 74 / 0.12)",
      "--card-background": "#ffffff",
      "--card-border": "#86efac",
      "--input-background": "#ffffff",
      "--input-border": "#86efac",
    },
  },
  {
    name: "暖色",
    description: "温暖橙色调主题，适合博客、 lifestyle 或创意页面",
    variables: {
      "--primary": "#ea580c",
      "--primary-foreground": "#ffffff",
      "--background": "#fffcf5",
      "--foreground": "#1c1917",
      "--muted": "#fff7ed",
      "--muted-foreground": "#78716c",
      "--accent": "#ffedd5",
      "--accent-foreground": "#9a3412",
      "--border": "#fed7aa",
      "--ring": "#ea580c",
      "--radius": "0.5rem",
      "--font-family": "Inter, system-ui, -apple-system, sans-serif",
      "--shadow-sm": "0 1px 2px 0 rgb(234 88 12 / 0.08)",
      "--shadow-md": "0 4px 6px -1px rgb(234 88 12 / 0.12)",
      "--card-background": "#ffffff",
      "--card-border": "#fed7aa",
      "--input-background": "#ffffff",
      "--input-border": "#fed7aa",
    },
  },
]
